package wg_media_data.es2ka.model.common.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyncCaibianData<M extends BaseSyncCaibianData<M>> extends Model<M> implements IBean {

	public void setAutoId(java.lang.Long autoId) {
		set("auto_id", autoId);
	}

	public java.lang.Long getAutoId() {
		return get("auto_id");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setWebsite(java.lang.String website) {
		set("website", website);
	}

	public java.lang.String getWebsite() {
		return get("website");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setPubtime(java.util.Date pubtime) {
		set("pubtime", pubtime);
	}

	public java.util.Date getPubtime() {
		return get("pubtime");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setPictures(java.lang.String pictures) {
		set("pictures", pictures);
	}

	public java.lang.String getPictures() {
		return get("pictures");
	}

	public void setColumnName(java.lang.String columnName) {
		set("column_name", columnName);
	}

	public java.lang.String getColumnName() {
		return get("column_name");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
