package wg_media_data.es2ka.model.common;

import wg_media_data.es2ka.model.common.base.BaseSyncCaibianData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyncCaibianData extends BaseSyncCaibianData<SyncCaibianData> {
	public static final SyncCaibianData dao = new SyncCaibianData().dao();
}
